// Generated by gencpp from file arduino_servo_connect/GetAllServoEnableResponse.msg
// DO NOT EDIT!


#ifndef ARDUINO_SERVO_CONNECT_MESSAGE_GETALLSERVOENABLERESPONSE_H
#define ARDUINO_SERVO_CONNECT_MESSAGE_GETALLSERVOENABLERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arduino_servo_connect
{
template <class ContainerAllocator>
struct GetAllServoEnableResponse_
{
  typedef GetAllServoEnableResponse_<ContainerAllocator> Type;

  GetAllServoEnableResponse_()
    : enables()  {
    }
  GetAllServoEnableResponse_(const ContainerAllocator& _alloc)
    : enables(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _enables_type;
  _enables_type enables;





  typedef boost::shared_ptr< ::arduino_servo_connect::GetAllServoEnableResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arduino_servo_connect::GetAllServoEnableResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetAllServoEnableResponse_

typedef ::arduino_servo_connect::GetAllServoEnableResponse_<std::allocator<void> > GetAllServoEnableResponse;

typedef boost::shared_ptr< ::arduino_servo_connect::GetAllServoEnableResponse > GetAllServoEnableResponsePtr;
typedef boost::shared_ptr< ::arduino_servo_connect::GetAllServoEnableResponse const> GetAllServoEnableResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arduino_servo_connect::GetAllServoEnableResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arduino_servo_connect::GetAllServoEnableResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace arduino_servo_connect

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'arduino_servo_connect': ['/home/bingo/face_tracker/ros_code/src/arduino_servo_connect/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::arduino_servo_connect::GetAllServoEnableResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arduino_servo_connect::GetAllServoEnableResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arduino_servo_connect::GetAllServoEnableResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arduino_servo_connect::GetAllServoEnableResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arduino_servo_connect::GetAllServoEnableResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arduino_servo_connect::GetAllServoEnableResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arduino_servo_connect::GetAllServoEnableResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fb3e3dbce60e36b185d663dfe470ce14";
  }

  static const char* value(const ::arduino_servo_connect::GetAllServoEnableResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfb3e3dbce60e36b1ULL;
  static const uint64_t static_value2 = 0x85d663dfe470ce14ULL;
};

template<class ContainerAllocator>
struct DataType< ::arduino_servo_connect::GetAllServoEnableResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arduino_servo_connect/GetAllServoEnableResponse";
  }

  static const char* value(const ::arduino_servo_connect::GetAllServoEnableResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arduino_servo_connect::GetAllServoEnableResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] enables\n\
\n\
";
  }

  static const char* value(const ::arduino_servo_connect::GetAllServoEnableResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arduino_servo_connect::GetAllServoEnableResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enables);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetAllServoEnableResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arduino_servo_connect::GetAllServoEnableResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arduino_servo_connect::GetAllServoEnableResponse_<ContainerAllocator>& v)
  {
    s << indent << "enables[]" << std::endl;
    for (size_t i = 0; i < v.enables.size(); ++i)
    {
      s << indent << "  enables[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.enables[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARDUINO_SERVO_CONNECT_MESSAGE_GETALLSERVOENABLERESPONSE_H
