// Generated by gencpp from file arduino_servo_connect/GetAllServoEnable.msg
// DO NOT EDIT!


#ifndef ARDUINO_SERVO_CONNECT_MESSAGE_GETALLSERVOENABLE_H
#define ARDUINO_SERVO_CONNECT_MESSAGE_GETALLSERVOENABLE_H

#include <ros/service_traits.h>


#include <arduino_servo_connect/GetAllServoEnableRequest.h>
#include <arduino_servo_connect/GetAllServoEnableResponse.h>


namespace arduino_servo_connect
{

struct GetAllServoEnable
{

typedef GetAllServoEnableRequest Request;
typedef GetAllServoEnableResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetAllServoEnable
} // namespace arduino_servo_connect


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arduino_servo_connect::GetAllServoEnable > {
  static const char* value()
  {
    return "fb3e3dbce60e36b185d663dfe470ce14";
  }

  static const char* value(const ::arduino_servo_connect::GetAllServoEnable&) { return value(); }
};

template<>
struct DataType< ::arduino_servo_connect::GetAllServoEnable > {
  static const char* value()
  {
    return "arduino_servo_connect/GetAllServoEnable";
  }

  static const char* value(const ::arduino_servo_connect::GetAllServoEnable&) { return value(); }
};


// service_traits::MD5Sum< ::arduino_servo_connect::GetAllServoEnableRequest> should match 
// service_traits::MD5Sum< ::arduino_servo_connect::GetAllServoEnable > 
template<>
struct MD5Sum< ::arduino_servo_connect::GetAllServoEnableRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arduino_servo_connect::GetAllServoEnable >::value();
  }
  static const char* value(const ::arduino_servo_connect::GetAllServoEnableRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arduino_servo_connect::GetAllServoEnableRequest> should match 
// service_traits::DataType< ::arduino_servo_connect::GetAllServoEnable > 
template<>
struct DataType< ::arduino_servo_connect::GetAllServoEnableRequest>
{
  static const char* value()
  {
    return DataType< ::arduino_servo_connect::GetAllServoEnable >::value();
  }
  static const char* value(const ::arduino_servo_connect::GetAllServoEnableRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arduino_servo_connect::GetAllServoEnableResponse> should match 
// service_traits::MD5Sum< ::arduino_servo_connect::GetAllServoEnable > 
template<>
struct MD5Sum< ::arduino_servo_connect::GetAllServoEnableResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arduino_servo_connect::GetAllServoEnable >::value();
  }
  static const char* value(const ::arduino_servo_connect::GetAllServoEnableResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arduino_servo_connect::GetAllServoEnableResponse> should match 
// service_traits::DataType< ::arduino_servo_connect::GetAllServoEnable > 
template<>
struct DataType< ::arduino_servo_connect::GetAllServoEnableResponse>
{
  static const char* value()
  {
    return DataType< ::arduino_servo_connect::GetAllServoEnable >::value();
  }
  static const char* value(const ::arduino_servo_connect::GetAllServoEnableResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARDUINO_SERVO_CONNECT_MESSAGE_GETALLSERVOENABLE_H
