// Generated by gencpp from file arduino_servo_connect/GetAllServoPosResponse.msg
// DO NOT EDIT!


#ifndef ARDUINO_SERVO_CONNECT_MESSAGE_GETALLSERVOPOSRESPONSE_H
#define ARDUINO_SERVO_CONNECT_MESSAGE_GETALLSERVOPOSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arduino_servo_connect
{
template <class ContainerAllocator>
struct GetAllServoPosResponse_
{
  typedef GetAllServoPosResponse_<ContainerAllocator> Type;

  GetAllServoPosResponse_()
    : positions()  {
    }
  GetAllServoPosResponse_(const ContainerAllocator& _alloc)
    : positions(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _positions_type;
  _positions_type positions;





  typedef boost::shared_ptr< ::arduino_servo_connect::GetAllServoPosResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arduino_servo_connect::GetAllServoPosResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetAllServoPosResponse_

typedef ::arduino_servo_connect::GetAllServoPosResponse_<std::allocator<void> > GetAllServoPosResponse;

typedef boost::shared_ptr< ::arduino_servo_connect::GetAllServoPosResponse > GetAllServoPosResponsePtr;
typedef boost::shared_ptr< ::arduino_servo_connect::GetAllServoPosResponse const> GetAllServoPosResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arduino_servo_connect::GetAllServoPosResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arduino_servo_connect::GetAllServoPosResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace arduino_servo_connect

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'arduino_servo_connect': ['/home/bingo/face_tracker/ros_code/src/arduino_servo_connect/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::arduino_servo_connect::GetAllServoPosResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arduino_servo_connect::GetAllServoPosResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arduino_servo_connect::GetAllServoPosResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arduino_servo_connect::GetAllServoPosResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arduino_servo_connect::GetAllServoPosResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arduino_servo_connect::GetAllServoPosResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arduino_servo_connect::GetAllServoPosResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a2a9139ca9bf4352767912894c0d0ece";
  }

  static const char* value(const ::arduino_servo_connect::GetAllServoPosResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa2a9139ca9bf4352ULL;
  static const uint64_t static_value2 = 0x767912894c0d0eceULL;
};

template<class ContainerAllocator>
struct DataType< ::arduino_servo_connect::GetAllServoPosResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arduino_servo_connect/GetAllServoPosResponse";
  }

  static const char* value(const ::arduino_servo_connect::GetAllServoPosResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arduino_servo_connect::GetAllServoPosResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] positions\n\
\n\
";
  }

  static const char* value(const ::arduino_servo_connect::GetAllServoPosResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arduino_servo_connect::GetAllServoPosResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.positions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetAllServoPosResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arduino_servo_connect::GetAllServoPosResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arduino_servo_connect::GetAllServoPosResponse_<ContainerAllocator>& v)
  {
    s << indent << "positions[]" << std::endl;
    for (size_t i = 0; i < v.positions.size(); ++i)
    {
      s << indent << "  positions[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.positions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARDUINO_SERVO_CONNECT_MESSAGE_GETALLSERVOPOSRESPONSE_H
