// Generated by gencpp from file arduino_servo_connect/GetAllServoPos.msg
// DO NOT EDIT!


#ifndef ARDUINO_SERVO_CONNECT_MESSAGE_GETALLSERVOPOS_H
#define ARDUINO_SERVO_CONNECT_MESSAGE_GETALLSERVOPOS_H

#include <ros/service_traits.h>


#include <arduino_servo_connect/GetAllServoPosRequest.h>
#include <arduino_servo_connect/GetAllServoPosResponse.h>


namespace arduino_servo_connect
{

struct GetAllServoPos
{

typedef GetAllServoPosRequest Request;
typedef GetAllServoPosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetAllServoPos
} // namespace arduino_servo_connect


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arduino_servo_connect::GetAllServoPos > {
  static const char* value()
  {
    return "a2a9139ca9bf4352767912894c0d0ece";
  }

  static const char* value(const ::arduino_servo_connect::GetAllServoPos&) { return value(); }
};

template<>
struct DataType< ::arduino_servo_connect::GetAllServoPos > {
  static const char* value()
  {
    return "arduino_servo_connect/GetAllServoPos";
  }

  static const char* value(const ::arduino_servo_connect::GetAllServoPos&) { return value(); }
};


// service_traits::MD5Sum< ::arduino_servo_connect::GetAllServoPosRequest> should match 
// service_traits::MD5Sum< ::arduino_servo_connect::GetAllServoPos > 
template<>
struct MD5Sum< ::arduino_servo_connect::GetAllServoPosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arduino_servo_connect::GetAllServoPos >::value();
  }
  static const char* value(const ::arduino_servo_connect::GetAllServoPosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arduino_servo_connect::GetAllServoPosRequest> should match 
// service_traits::DataType< ::arduino_servo_connect::GetAllServoPos > 
template<>
struct DataType< ::arduino_servo_connect::GetAllServoPosRequest>
{
  static const char* value()
  {
    return DataType< ::arduino_servo_connect::GetAllServoPos >::value();
  }
  static const char* value(const ::arduino_servo_connect::GetAllServoPosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arduino_servo_connect::GetAllServoPosResponse> should match 
// service_traits::MD5Sum< ::arduino_servo_connect::GetAllServoPos > 
template<>
struct MD5Sum< ::arduino_servo_connect::GetAllServoPosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arduino_servo_connect::GetAllServoPos >::value();
  }
  static const char* value(const ::arduino_servo_connect::GetAllServoPosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arduino_servo_connect::GetAllServoPosResponse> should match 
// service_traits::DataType< ::arduino_servo_connect::GetAllServoPos > 
template<>
struct DataType< ::arduino_servo_connect::GetAllServoPosResponse>
{
  static const char* value()
  {
    return DataType< ::arduino_servo_connect::GetAllServoPos >::value();
  }
  static const char* value(const ::arduino_servo_connect::GetAllServoPosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARDUINO_SERVO_CONNECT_MESSAGE_GETALLSERVOPOS_H
