// Generated by gencpp from file arduino_servo_connect/MoveServo.msg
// DO NOT EDIT!


#ifndef ARDUINO_SERVO_CONNECT_MESSAGE_MOVESERVO_H
#define ARDUINO_SERVO_CONNECT_MESSAGE_MOVESERVO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace arduino_servo_connect
{
template <class ContainerAllocator>
struct MoveServo_
{
  typedef MoveServo_<ContainerAllocator> Type;

  MoveServo_()
    : header()
    , servoId(0)
    , targetPos(0)
    , delay(0)  {
    }
  MoveServo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , servoId(0)
    , targetPos(0)
    , delay(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _servoId_type;
  _servoId_type servoId;

   typedef uint16_t _targetPos_type;
  _targetPos_type targetPos;

   typedef uint8_t _delay_type;
  _delay_type delay;





  typedef boost::shared_ptr< ::arduino_servo_connect::MoveServo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arduino_servo_connect::MoveServo_<ContainerAllocator> const> ConstPtr;

}; // struct MoveServo_

typedef ::arduino_servo_connect::MoveServo_<std::allocator<void> > MoveServo;

typedef boost::shared_ptr< ::arduino_servo_connect::MoveServo > MoveServoPtr;
typedef boost::shared_ptr< ::arduino_servo_connect::MoveServo const> MoveServoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arduino_servo_connect::MoveServo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arduino_servo_connect::MoveServo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace arduino_servo_connect

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'arduino_servo_connect': ['/home/bingo/face_tracker/ros_code/src/arduino_servo_connect/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::arduino_servo_connect::MoveServo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arduino_servo_connect::MoveServo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arduino_servo_connect::MoveServo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arduino_servo_connect::MoveServo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arduino_servo_connect::MoveServo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arduino_servo_connect::MoveServo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arduino_servo_connect::MoveServo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a4ff497aa19abc6e9d982bd9133ef9b7";
  }

  static const char* value(const ::arduino_servo_connect::MoveServo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa4ff497aa19abc6eULL;
  static const uint64_t static_value2 = 0x9d982bd9133ef9b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::arduino_servo_connect::MoveServo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arduino_servo_connect/MoveServo";
  }

  static const char* value(const ::arduino_servo_connect::MoveServo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arduino_servo_connect::MoveServo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Move Servo msg, include three param: servoid, targetPos, delay\n\
Header header\n\
\n\
uint8 servoId\n\
uint16 targetPos\n\
uint8 delay\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::arduino_servo_connect::MoveServo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arduino_servo_connect::MoveServo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.servoId);
      stream.next(m.targetPos);
      stream.next(m.delay);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveServo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arduino_servo_connect::MoveServo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arduino_servo_connect::MoveServo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "servoId: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.servoId);
    s << indent << "targetPos: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.targetPos);
    s << indent << "delay: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.delay);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARDUINO_SERVO_CONNECT_MESSAGE_MOVESERVO_H
