// Generated by gencpp from file arduino_servo_connect/ServoEnable.msg
// DO NOT EDIT!


#ifndef ARDUINO_SERVO_CONNECT_MESSAGE_SERVOENABLE_H
#define ARDUINO_SERVO_CONNECT_MESSAGE_SERVOENABLE_H

#include <ros/service_traits.h>


#include <arduino_servo_connect/ServoEnableRequest.h>
#include <arduino_servo_connect/ServoEnableResponse.h>


namespace arduino_servo_connect
{

struct ServoEnable
{

typedef ServoEnableRequest Request;
typedef ServoEnableResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ServoEnable
} // namespace arduino_servo_connect


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arduino_servo_connect::ServoEnable > {
  static const char* value()
  {
    return "bdf13954fac71cd1ad130cc58e64cb5e";
  }

  static const char* value(const ::arduino_servo_connect::ServoEnable&) { return value(); }
};

template<>
struct DataType< ::arduino_servo_connect::ServoEnable > {
  static const char* value()
  {
    return "arduino_servo_connect/ServoEnable";
  }

  static const char* value(const ::arduino_servo_connect::ServoEnable&) { return value(); }
};


// service_traits::MD5Sum< ::arduino_servo_connect::ServoEnableRequest> should match 
// service_traits::MD5Sum< ::arduino_servo_connect::ServoEnable > 
template<>
struct MD5Sum< ::arduino_servo_connect::ServoEnableRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arduino_servo_connect::ServoEnable >::value();
  }
  static const char* value(const ::arduino_servo_connect::ServoEnableRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arduino_servo_connect::ServoEnableRequest> should match 
// service_traits::DataType< ::arduino_servo_connect::ServoEnable > 
template<>
struct DataType< ::arduino_servo_connect::ServoEnableRequest>
{
  static const char* value()
  {
    return DataType< ::arduino_servo_connect::ServoEnable >::value();
  }
  static const char* value(const ::arduino_servo_connect::ServoEnableRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arduino_servo_connect::ServoEnableResponse> should match 
// service_traits::MD5Sum< ::arduino_servo_connect::ServoEnable > 
template<>
struct MD5Sum< ::arduino_servo_connect::ServoEnableResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arduino_servo_connect::ServoEnable >::value();
  }
  static const char* value(const ::arduino_servo_connect::ServoEnableResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arduino_servo_connect::ServoEnableResponse> should match 
// service_traits::DataType< ::arduino_servo_connect::ServoEnable > 
template<>
struct DataType< ::arduino_servo_connect::ServoEnableResponse>
{
  static const char* value()
  {
    return DataType< ::arduino_servo_connect::ServoEnable >::value();
  }
  static const char* value(const ::arduino_servo_connect::ServoEnableResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARDUINO_SERVO_CONNECT_MESSAGE_SERVOENABLE_H
