// Generated by gencpp from file arduino_servo_connect/ServoWrite.msg
// DO NOT EDIT!


#ifndef ARDUINO_SERVO_CONNECT_MESSAGE_SERVOWRITE_H
#define ARDUINO_SERVO_CONNECT_MESSAGE_SERVOWRITE_H

#include <ros/service_traits.h>


#include <arduino_servo_connect/ServoWriteRequest.h>
#include <arduino_servo_connect/ServoWriteResponse.h>


namespace arduino_servo_connect
{

struct ServoWrite
{

typedef ServoWriteRequest Request;
typedef ServoWriteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ServoWrite
} // namespace arduino_servo_connect


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arduino_servo_connect::ServoWrite > {
  static const char* value()
  {
    return "cfb890a96d9d635807919eed49fd22d8";
  }

  static const char* value(const ::arduino_servo_connect::ServoWrite&) { return value(); }
};

template<>
struct DataType< ::arduino_servo_connect::ServoWrite > {
  static const char* value()
  {
    return "arduino_servo_connect/ServoWrite";
  }

  static const char* value(const ::arduino_servo_connect::ServoWrite&) { return value(); }
};


// service_traits::MD5Sum< ::arduino_servo_connect::ServoWriteRequest> should match 
// service_traits::MD5Sum< ::arduino_servo_connect::ServoWrite > 
template<>
struct MD5Sum< ::arduino_servo_connect::ServoWriteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arduino_servo_connect::ServoWrite >::value();
  }
  static const char* value(const ::arduino_servo_connect::ServoWriteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arduino_servo_connect::ServoWriteRequest> should match 
// service_traits::DataType< ::arduino_servo_connect::ServoWrite > 
template<>
struct DataType< ::arduino_servo_connect::ServoWriteRequest>
{
  static const char* value()
  {
    return DataType< ::arduino_servo_connect::ServoWrite >::value();
  }
  static const char* value(const ::arduino_servo_connect::ServoWriteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arduino_servo_connect::ServoWriteResponse> should match 
// service_traits::MD5Sum< ::arduino_servo_connect::ServoWrite > 
template<>
struct MD5Sum< ::arduino_servo_connect::ServoWriteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arduino_servo_connect::ServoWrite >::value();
  }
  static const char* value(const ::arduino_servo_connect::ServoWriteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arduino_servo_connect::ServoWriteResponse> should match 
// service_traits::DataType< ::arduino_servo_connect::ServoWrite > 
template<>
struct DataType< ::arduino_servo_connect::ServoWriteResponse>
{
  static const char* value()
  {
    return DataType< ::arduino_servo_connect::ServoWrite >::value();
  }
  static const char* value(const ::arduino_servo_connect::ServoWriteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARDUINO_SERVO_CONNECT_MESSAGE_SERVOWRITE_H
