// Generated by gencpp from file arduino_servo_connect/ServoRead.msg
// DO NOT EDIT!


#ifndef ARDUINO_SERVO_CONNECT_MESSAGE_SERVOREAD_H
#define ARDUINO_SERVO_CONNECT_MESSAGE_SERVOREAD_H

#include <ros/service_traits.h>


#include <arduino_servo_connect/ServoReadRequest.h>
#include <arduino_servo_connect/ServoReadResponse.h>


namespace arduino_servo_connect
{

struct ServoRead
{

typedef ServoReadRequest Request;
typedef ServoReadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ServoRead
} // namespace arduino_servo_connect


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arduino_servo_connect::ServoRead > {
  static const char* value()
  {
    return "da1b9d707f4bc75aeccfced2e0cd2663";
  }

  static const char* value(const ::arduino_servo_connect::ServoRead&) { return value(); }
};

template<>
struct DataType< ::arduino_servo_connect::ServoRead > {
  static const char* value()
  {
    return "arduino_servo_connect/ServoRead";
  }

  static const char* value(const ::arduino_servo_connect::ServoRead&) { return value(); }
};


// service_traits::MD5Sum< ::arduino_servo_connect::ServoReadRequest> should match 
// service_traits::MD5Sum< ::arduino_servo_connect::ServoRead > 
template<>
struct MD5Sum< ::arduino_servo_connect::ServoReadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arduino_servo_connect::ServoRead >::value();
  }
  static const char* value(const ::arduino_servo_connect::ServoReadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arduino_servo_connect::ServoReadRequest> should match 
// service_traits::DataType< ::arduino_servo_connect::ServoRead > 
template<>
struct DataType< ::arduino_servo_connect::ServoReadRequest>
{
  static const char* value()
  {
    return DataType< ::arduino_servo_connect::ServoRead >::value();
  }
  static const char* value(const ::arduino_servo_connect::ServoReadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arduino_servo_connect::ServoReadResponse> should match 
// service_traits::MD5Sum< ::arduino_servo_connect::ServoRead > 
template<>
struct MD5Sum< ::arduino_servo_connect::ServoReadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arduino_servo_connect::ServoRead >::value();
  }
  static const char* value(const ::arduino_servo_connect::ServoReadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arduino_servo_connect::ServoReadResponse> should match 
// service_traits::DataType< ::arduino_servo_connect::ServoRead > 
template<>
struct DataType< ::arduino_servo_connect::ServoReadResponse>
{
  static const char* value()
  {
    return DataType< ::arduino_servo_connect::ServoRead >::value();
  }
  static const char* value(const ::arduino_servo_connect::ServoReadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARDUINO_SERVO_CONNECT_MESSAGE_SERVOREAD_H
